### ISSUE TITLE
最后一步报错啊，兄弟

### ISSUE THREAD

**Issue by jxbtsj** [natureLanguageQing/generative_paddle#1]
(paddle) C:\Users\David\Desktop\duconv\generative_paddle>python -u network.py --run_type train  --stage 0  --use_gpu True  --pretrain_epoch 5 --batch_size 32  --use_posterior True --save_dir models --vocab_path data\vocab.txt --embed_file data\sgns.weibo.300d.txt
stage 0
Traceback (most recent call last):
  File "network.py", line 518, in <module>
    train(config)
  File "network.py", line 469, in train
    optimizer.minimize(bow_loss)
  File "<C:\ProgramData\Anaconda3\envs\paddle\lib\site-packages\decorator.py:decorator-gen-20>", line 2, in minimize
  File "C:\ProgramData\Anaconda3\envs\paddle\lib\site-packages\paddle\fluid\wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\paddle\lib\site-packages\paddle\fluid\dygraph\base.py", line 87, in __impl__
    return func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\paddle\lib\site-packages\paddle\fluid\optimizer.py", line 594, in minimize
    no_grad_set=no_grad_set)
  File "C:\ProgramData\Anaconda3\envs\paddle\lib\site-packages\paddle\fluid\optimizer.py", line 493, in backward
    no_grad_set, callbacks)
  File "C:\ProgramData\Anaconda3\envs\paddle\lib\site-packages\paddle\fluid\backward.py", line 578, in append_backward
    _append_backward_vars_(root_block, fwd_op_num, grad_to_var, grad_info_map)
  File "C:\ProgramData\Anaconda3\envs\paddle\lib\site-packages\paddle\fluid\backward.py", line 392, in _append_backward_vars_
    op_desc.infer_shape(block.desc)
paddle.fluid.core_avx.EnforceNotMet: Enforce failed. Expected x_dims[i] * expand_times[i] == out_dims[i], but received x_dims[i] * expand_times[i]:-500 != out_dims[i]:-1.
Each dimension size of Input(Out@GRAD) should be equal to multiplication of crroresponding dimension size of Input(X) and Attr(expand_times) value. at [D:\1.5.1\release_cuda97\paddle\paddle\fluid\operators\expand_op.cc:153]

**Comment by jxbtsj** [comment]
@natureLanguageQing 帮忙看下，我用的是python3.7， paddle是1.5.1
